### PR TITLE
Loosen yarn engines restriction to >= 1.16.0

### PR DESCRIPTION
**Pull request by scottkidder**
I'm currently on yarn 1.17.3 and everything is working great. I was unsure if there are any other considerations for freezing this at 1.16.0.

### CODE REVIEW

**Comment by scottkidder** [comment]
@charlesdemers This is blocking us from upgrading (we are unable to sprinkle --ignore-engines everywhere). Any chance we get this merged?

**Comment by charlesdemers** [comment]
Sorry for the delay, thanks for the contribution! I'll publish a new version in a few minutes.

**Comment by charlesdemers** [comment]
@scottkidder Version 1.0.7 is published on npm 🎉

**Comment by scottkidder** [comment]
Thanks!

**Pull request merged**
